/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.122
 * Generated at: 2026-10-05 03:18:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>SaludClick - Iniciar Sesión</title>\n");
      out.write("    <style>\n");
      out.write("        * { box-sizing: border-box; margin: 0; padding: 0; font-family: 'Segoe UI', system-ui, sans-serif; }\n");
      out.write("        /* 1. CONTENEDOR PRINCIPAL: Asegura el ancho completo */\n");
      out.write("        .page-container { \n");
      out.write("            display: flex; \n");
      out.write("            min-height: 100vh; \n");
      out.write("            width: 100%; /* Asegura que ocupe toda la pantalla */\n");
      out.write("            overflow: hidden;\n");
      out.write("            background-color: #ffffff; \n");
      out.write("}\n");
      out.write("\n");
      out.write("        /* COLUMNA IZQUIERDA: Imagen limpia  */\n");
      out.write("         .left-side { \n");
      out.write("            width: 55%; \n");
      out.write("            background-image: url('img/fondo.jpg'); \n");
      out.write("            background-size: cover; \n");
      out.write("            background-position: center center;\n");
      out.write("            background-repeat: no-repeat; /* Evita que la foto se duplique */\n");
      out.write("            border-top-right-radius: 40px;\n");
      out.write("            flex-shrink: 0; /* OBLIGATORIO: Evita que el navegador encoja o corte esta columna */\n");
      out.write("}\n");
      out.write("\n");
      out.write("        /* COLUMNA DERECHA: Formulario  */\n");
      out.write("         .right-side { \n");
      out.write("            width: 45%; \n");
      out.write("            height: 100%;\n");
      out.write("            display: flex; \n");
      out.write("            justify-content: center; \n");
      out.write("            align-items: center; \n");
      out.write("            padding: 0 60px; \n");
      out.write("            background-color: #ffffff;\n");
      out.write("            flex-shrink: 0; /* OBLIGATORIO: Evita que se encoja el lado del formulario */\n");
      out.write("}\n");
      out.write("        \n");
      out.write("        /* 4. CAJA BLANCA DEL LOGIN:*/\n");
      out.write("        .form-box { \n");
      out.write("            width: 100%; \n");
      out.write("            max-width: 480px; \n");
      out.write("            background: transparent; \n");
      out.write("            padding: 45px 40px; \n");
      out.write("            padding: 0; \n");
      out.write("            box-shadow: none; \n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* CONTENEDOR DEL LOGO AGRANDADO */\n");
      out.write("        .logo-container { \n");
      out.write("            text-align: center; \n");
      out.write("            margin-top: 50px;\n");
      out.write("            margin-bottom: 20px; \n");
      out.write("        }\n");
      out.write("        .logo-container img { \n");
      out.write("            width: 350px; /* <--- Agrandamos considerablemente tu logo de SaludClick */\n");
      out.write("            height: auto; \n");
      out.write("            object-fit: contain;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* 5. TAMAÑO DE LOS TEXTOS INTERNOS: iniciar sesion */\n");
      out.write("        .form-box h2 { \n");
      out.write("            color: #000000; \n");
      out.write("            font-size: 3rem; \n");
      out.write("            margin-bottom: 30px; \n");
      out.write("            font-weight: 700; \n");
      out.write("            text-align: center; \n");
      out.write("        }\n");
      out.write("        /* 6. LABELS E INPUTS GIGANTES: letra documento y contra */\n");
      out.write("        label { \n");
      out.write("            display: block; \n");
      out.write("            font-weight: 600; \n");
      out.write("            margin-bottom: 8px; \n");
      out.write("            color: #475569; \n");
      out.write("            font-size: 1.5rem; \n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* Campos de texto más grandes y cómodos para el usuario */\n");
      out.write("        .document-group { \n");
      out.write("            display: flex; \n");
      out.write("            margin-bottom: 25px; \n");
      out.write("            border: 1.5px solid #cbd5e1; \n");
      out.write("            border-radius: 10px; \n");
      out.write("            overflow: hidden; \n");
      out.write("        }\n");
      out.write("        .document-group:focus-within { border-color: #2563eb; }\n");
      out.write("\n");
      out.write("        /* Selector e input más altos y espaciosos */\n");
      out.write("        .document-group select { border: none; padding: 18px 15px; background: #ffffff; font-size: 1.3rem; color: #000000; font-weight: 600; outline: none; border-right: 1.5px solid #cbd5e1; cursor: pointer; }\n");
      out.write("        .document-group input { border: none; width: 100%; padding: 18px 20px; font-size: 1.15rem; outline: none; }\n");
      out.write("\n");
      out.write("        .normal-input { \n");
      out.write("            width: 100%; \n");
      out.write("            padding: 18px 20px; \n");
      out.write("            margin-bottom: 35px; \n");
      out.write("            border: 1.5px solid #cbd5e1; \n");
      out.write("            border-radius: 10px; \n");
      out.write("            font-size: 1.15rem; \n");
      out.write("            outline: none; \n");
      out.write("        }\n");
      out.write("        .normal-input:focus { border-color: #2563eb; }\n");
      out.write("\n");
      out.write("        /* 7. BOTÓN INGRESAR ROBUSTO Y REDONDEADO */\n");
      out.write("        button { \n");
      out.write("            width: 100%; \n");
      out.write("            background-color: #1a56db; \n");
      out.write("            color: white; \n");
      out.write("            padding: 12px; \n");
      out.write("            border: none; \n");
      out.write("            border-radius: 30px; /* <--- Botón en forma de óvalo idéntico al de la clínica */\n");
      out.write("            font-size: 2.2rem; \n");
      out.write("            font-weight: bold; \n");
      out.write("            cursor: pointer; \n");
      out.write("            transition: background 0.2s; \n");
      out.write("        }\n");
      out.write("        button:hover { background-color: #1e429f; }\n");
      out.write("\n");
      out.write("        .footer-links { margin-top: 35px; text-align: center; font-size: 1.05rem; color: #475569; }\n");
      out.write("        .footer-links a { color: #1a56db; text-decoration: none; font-weight: 700; }\n");
      out.write("\n");
      out.write("        @media (max-width: 900px) {\n");
      out.write("            .page-container { flex-direction: column; }\n");
      out.write("            .left-side, .right-side { width: 100%; min-height: auto; }\n");
      out.write("            .left-side { height: 300px; padding: 20px; }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"page-container\">\n");
      out.write("        \n");
      out.write("        <!-- COLUMNA IZQUIERDA: Aquí va tu imagen familiar limpia (45% del ancho) -->\n");
      out.write("        <div class=\"left-side\"></div>\n");
      out.write("        \n");
      out.write("        <!-- COLUMNA DERECHA: Aquí va tu caja de login ampliada (55% del ancho) -->\n");
      out.write("        <div class=\"right-side\">\n");
      out.write("            <div class=\"form-box\">\n");
      out.write("                \n");
      out.write("                <!-- Tu logotipo de SaludClick en tamaño grande -->\n");
      out.write("                <div class=\"logo-container\">\n");
      out.write("                    <img src=\"img/logo1.png\" alt=\"Logo SaludClick\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <h2>Iniciar sesión</h2>\n");
      out.write("                                \n");
      out.write("                <form action=\"LoginServlet\" method=\"POST\">\n");
      out.write("                    <label>Documento de Identidad:</label>\n");
      out.write("                    <div class=\"document-group\">\n");
      out.write("                        <select name=\"tipoDocumento\">\n");
      out.write("                            <option value=\"DNI\">DNI</option>\n");
      out.write("                            <option value=\"CE\">C.E.</option>\n");
      out.write("                            <option value=\"PASAPORTE\">Pasaporte</option>\n");
      out.write("                        </select>\n");
      out.write("                        <input type=\"text\" name=\"numeroDocumento\" required placeholder=\"Nro de documento\">\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <label for=\"password\">Contraseña:</label>\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"password\" class=\"normal-input\" required placeholder=\"Contraseña\">\n");
      out.write("\n");
      out.write("                    <button type=\"submit\">Ingresar</button>\n");
      out.write("                </form>\n");
      out.write("                \n");
      out.write("                <div class=\"footer-links\">\n");
      out.write("                    ¿No tienes cuenta? <a href=\"registro_paciente.jsp\">Crear cuenta</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
