/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.122
 * Generated at: 2026-10-05 03:18:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Conexion.ConexionDB;

public final class panel_005fpaciente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 
    private String examinarTexto(String texto) {
        return texto != null ? texto : "";
    }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("Conexion.ConexionDB");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    // 1. Intentamos recuperar el DNI guardado en la sesión
    String dniSesion = (String) session.getAttribute("usuarioDni");
    
    // 2. Control de seguridad: Si alguien intenta entrar al panel sin loguearse, lo botamos al login
    if (dniSesion == null) {
        response.sendRedirect("login.jsp");
        return; 
    }

    // 3. Consultar el nombre del paciente en la BD
    String nombrePaciente = "Paciente";
    Connection conNom = null;
    PreparedStatement psNom = null;
    ResultSet rsNom = null;
    try {
        conNom = Conexion.ConexionDB.conectar();
        String sqlNom = "SELECT nombres FROM pacientes WHERE numero_documento = ?";
        psNom = conNom.prepareStatement(sqlNom);
        psNom.setString(1, dniSesion);
        rsNom = psNom.executeQuery();
        if (rsNom.next()) {
            nombrePaciente = rsNom.getString("nombres");
        }
    } catch(Exception e) {
        nombrePaciente = "Paciente";
    } finally {
        if(rsNom != null) rsNom.close();
        if(psNom != null) psNom.close();
        if(conNom != null) conNom.close();
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>SaludClick - Panel del Paciente</title>\n");
      out.write("    <style>\n");
      out.write("        * { box-sizing: border-box; margin: 0; padding: 0; font-family: 'Segoe UI', system-ui, sans-serif; }\n");
      out.write("        body { background-color: #f1f5f9; color: #1e293b; display: flex; min-height: 100vh; }\n");
      out.write("        \n");
      out.write("        /* Barra Lateral Izquierda */\n");
      out.write("        .sidebar { width: 260px; background-color: #1e3a8a; color: white; padding: 30px 20px; display: flex; flex-direction: column; }\n");
      out.write("        .sidebar h2 { font-size: 1.5rem; margin-bottom: 40px; text-align: center; font-weight: 700; }\n");
      out.write("        /* Logo blanco para que resalte en el fondo azul */\n");
      out.write("        .sidebar h2 img { width: 140px; height: auto; filter: invert(1) brightness(200%); }\n");
      out.write("        .sidebar a { color: #93c5fd; text-decoration: none; padding: 12px 15px; border-radius: 8px; margin-bottom: 10px; font-weight: 600; transition: all 0.2s; }\n");
      out.write("        .sidebar a.active, .sidebar a:hover { background-color: #1d4ed8; color: white; }\n");
      out.write("        .sidebar .logout { margin-top: auto; background-color: #b91c1c; color: white; text-align: center; }\n");
      out.write("        .sidebar .logout:hover { background-color: #991b1b; }\n");
      out.write("\n");
      out.write("        /* Contenedor Principal Derecho */\n");
      out.write("        .main-content { flex: 1; padding: 40px; overflow-y: auto; }\n");
      out.write("        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 25px; border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; }\n");
      out.write("        .header h1 { font-size: 1.8rem; color: #0f172a; }\n");
      out.write("        \n");
      out.write("        /* Barra superior de Establecimientos a todo el ancho */\n");
      out.write("        .banner-establecimientos { background: white; padding: 20px 25px; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05); margin-bottom: 30px; }\n");
      out.write("        .banner-establecimientos h4 { color: #1e3a8a; font-size: 1rem; margin-bottom: 12px; display: flex; align-items: center; gap: 8px; }\n");
      out.write("        .establecimientos-grid { display: flex; gap: 15px; overflow-x: auto; padding-bottom: 5px; }\n");
      out.write("        .est-badge { background: #f8fafc; border: 1.5px solid #e2e8f0; padding: 10px 18px; border-radius: 8px; font-weight: 600; color: #2563eb; white-space: nowrap; font-size: 0.9rem; display: flex; align-items: center; gap: 6px; }\n");
      out.write("\n");
      out.write("        /* Grid de dos columnas */\n");
      out.write("        .dashboard-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 30px; }\n");
      out.write("        @media (max-width: 1024px) { .dashboard-grid { grid-template-columns: 1fr; } }\n");
      out.write("\n");
      out.write("        /* Tarjetas contenedoras */\n");
      out.write("        .card { background: white; padding: 30px; border-radius: 16px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05); }\n");
      out.write("        .card h3 { color: #1e3a8a; font-size: 1.3rem; margin-bottom: 20px; border-bottom: 1px solid #f1f5f9; padding-bottom: 10px; }\n");
      out.write("\n");
      out.write("        /* Formulario de Citas */\n");
      out.write("        label { display: block; font-weight: 600; margin-bottom: 8px; color: #475569; font-size: 0.9rem; }\n");
      out.write("        select, input { width: 100%; padding: 12px; margin-bottom: 20px; border: 1.5px solid #cbd5e1; border-radius: 8px; font-size: 1rem; outline: none; background-color: #fff; }\n");
      out.write("        select:focus, input:focus { border-color: #2563eb; box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.1); }\n");
      out.write("        button { width: 100%; background-color: #10b981; color: white; padding: 14px; border: none; border-radius: 8px; font-size: 1rem; font-weight: bold; cursor: pointer; transition: background 0.2s; }\n");
      out.write("        button:hover { background-color: #059669; }\n");
      out.write("\n");
      out.write("        /* Lista de Citas */\n");
      out.write("        .appointment-item { background: #f8fafc; border-left: 5px solid #2563eb; padding: 15px; border-radius: 0 8px 8px 0; margin-bottom: 15px; display: flex; justify-content: space-between; align-items: center; }\n");
      out.write("        .appointment-info h4 { color: #1e293b; font-size: 1.05rem; }\n");
      out.write("        .appointment-info p { color: #64748b; font-size: 0.9rem; margin-top: 4px; }\n");
      out.write("        .status-badge { background-color: #dbeafe; color: #1e40af; padding: 6px 12px; border-radius: 20px; font-size: 0.8rem; font-weight: 700; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- Menú Lateral -->        \n");
      out.write("    <div class=\"sidebar\">\n");
      out.write("        <h2><img src=\"img/logo1.png\" alt=\"SaludClick Logo\"></h2>\n");
      out.write("        <a href=\"panel_paciente.jsp\" class=\"active\">📅 Mis Citas</a>\n");
      out.write("        <a href=\"perfil_paciente.jsp\">👤 Mi Perfil</a>\n");
      out.write("        <a href=\"clinicas_postas.jsp\">🏥 Clínicas y Postas</a>\n");
      out.write("        <a href=\"login.jsp\" class=\"logout\">Cerrar Sesión</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Contenido Principal -->\n");
      out.write("    <div class=\"main-content\">\n");
      out.write("        <div class=\"header\">\n");
      out.write("            <h1>Bienvenido(a), ");
      out.print( nombrePaciente );
      out.write("</h1>\n");
      out.write("            <p style=\"color: #64748b; font-weight: 600;\">🇵🇪 Sistema Nacional de Citas</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- BARRA A TODO EL ANCHO: Establecimientos Registrados en la BD -->\n");
      out.write("        <div class=\"banner-establecimientos\">\n");
      out.write("            <h4>🏥 Establecimientos y Clínicas Asociadas Registradas en la Plataforma:</h4>\n");
      out.write("            <div class=\"establecimientos-grid\">\n");
      out.write("                ");

                    Connection conBanner = null;
                    Statement stBanner = null;
                    ResultSet rsBanner = null;
                    try {
                        conBanner = Conexion.ConexionDB.conectar();
                        stBanner = conBanner.createStatement();
                        rsBanner = stBanner.executeQuery("SELECT nombre FROM establecimientos ORDER BY nombre");
                        while(rsBanner.next()) {
                
      out.write("\n");
      out.write("                            <div class=\"est-badge\">\n");
      out.write("                                ⭐ ");
      out.print( rsBanner.getString("nombre") );
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                ");

                        }
                    } catch(Exception e) {
                        out.println("<p style='color:red; font-size:0.9rem;'>No se pudieron cargar los establecimientos.</p>");
                    } finally {
                        if(rsBanner != null) rsBanner.close();
                        if(stBanner != null) stBanner.close();
                        if(conBanner != null) conBanner.close();
                    }
                
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"dashboard-grid\">\n");
      out.write("            \n");
      out.write("            <!-- COLUMNA 1: Formulario para Programar Cita -->\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <h3>Agendar Nueva Cita</h3>\n");
      out.write("                <form action=\"ProgramarCitaServlet\" method=\"POST\">\n");
      out.write("\n");
      out.write("                    <input type=\"hidden\" name=\"numeroDocumento\" value=\"");
      out.print(dniSesion);
      out.write("\"> \n");
      out.write("\n");
      out.write("                    <!-- 1. COMBOBOX: Establecimiento -->\n");
      out.write("                    <label for=\"idEstablecimiento\">1. Seleccione el Establecimiento de Salud:</label>\n");
      out.write("                    <select id=\"idEstablecimiento\" onchange=\"cargarEspecialidades()\" required>\n");
      out.write("                        <option value=\"\">-- Seleccione un establecimiento --</option>\n");
      out.write("                        ");

                            Connection conEst = null;
                            Statement stEst = null;
                            ResultSet rsEst = null;
                            try {
                                conEst = Conexion.ConexionDB.conectar();
                                stEst = conEst.createStatement();
                                rsEst = stEst.executeQuery("SELECT id, nombre FROM establecimientos ORDER BY nombre");
                                while(rsEst.next()) {
                        
      out.write("\n");
      out.write("                                    <option value=\"");
      out.print( rsEst.getInt("id") );
      out.write('"');
      out.write('>');
      out.print( rsEst.getString("nombre") );
      out.write("</option>\n");
      out.write("                        ");

                                }
                            } catch(Exception e) {} finally { if(rsEst!=null)rsEst.close(); if(stEst!=null)stEst.close(); if(conEst!=null)conEst.close(); }
                        
      out.write("\n");
      out.write("                    </select>\n");
      out.write("\n");
      out.write("                    <!-- 2. COMBOBOX: Especialidad -->\n");
      out.write("                    <label for=\"especialidadSelect\">2. Seleccione la Especialidad Médica:</label>\n");
      out.write("                    <select id=\"especialidadSelect\" onchange=\"cargarMedicos()\" disabled required>\n");
      out.write("                        <option value=\"\">-- Primero elija un establecimiento --</option>\n");
      out.write("                    </select>\n");
      out.write("\n");
      out.write("                    <!-- 3. COMBOBOX: Médico -->\n");
      out.write("                    <label for=\"idMedico\">3. Seleccione el Médico Disponible:</label>\n");
      out.write("                    <select id=\"idMedico\" name=\"idMedico\" disabled required>\n");
      out.write("                        <option value=\"\">-- Primero elija una especialidad --</option>\n");
      out.write("                    </select>\n");
      out.write("\n");
      out.write("                    <label for=\"fecha\">Fecha de la Cita:</label>\n");
      out.write("                    <input type=\"date\" id=\"fecha\" name=\"fecha\" required>\n");
      out.write("\n");
      out.write("                    <label for=\"hora\">Horario Disponible:</label>\n");
      out.write("                    <select id=\"hora\" name=\"hora\" required>\n");
      out.write("                        <option value=\"\">-- Seleccione la hora --</option>\n");
      out.write("                        <option value=\"08:00:00\">08:00 AM</option>\n");
      out.write("                        <option value=\"10:00:00\">10:00 AM</option>\n");
      out.write("                        <option value=\"14:00:00\">02:00 PM</option>\n");
      out.write("                        <option value=\"16:00:00\">04:30 PM</option>\n");
      out.write("                    </select>\n");
      out.write("\n");
      out.write("                    <button type=\"submit\">Confirmar Cita Médica</button>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- COLUMNA 2: Visualización de Próximas Citas -->\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <h3>Mis Citas Programadas</h3>\n");
      out.write("\n");
      out.write("            ");

                Connection conCitas = null;
                PreparedStatement psCitas = null;
                ResultSet rsCitas = null;

                try {
                    conCitas = Conexion.ConexionDB.conectar();
                    String sqlCitas = "SELECT c.fecha_cita, c.hora_cita, c.estado, m.especialidad, m.nombres AS medico_nombre, e.nombre AS est_nombre " +
                                        "FROM citas c " +
                                        "INNER JOIN medicos m ON c.id_medico = m.id " +
                                        "INNER JOIN establecimientos e ON m.id_establecimiento = e.id " +
                                        "WHERE c.numero_documento = ? " +
                                        "ORDER BY c.fecha_cita ASC, c.hora_cita ASC";

                    psCitas = conCitas.prepareStatement(sqlCitas);
                    psCitas.setString(1, dniSesion);
                    rsCitas = psCitas.executeQuery();

                    boolean tieneCitas = false;
                    while(rsCitas.next()) {
                        tieneCitas = true;
                        String especialidadCita = rsCitas.getString("especialidad");
                        String establecimientoCita = rsCitas.getString("est_nombre");
                        String medicoCita = rsCitas.getString("medico_nombre");
                        String fechaCita = rsCitas.getString("fecha_cita");
                        String horaCita = rsCitas.getString("hora_cita");
                        String estadoCita = rsCitas.getString("estado");

                        String colorBorde = estadoCita.equals("Atendida") ? "#10b981" : "#2563eb";
                        String estiloBadge = estadoCita.equals("Atendida") ? "background-color: #d1fae5; color: #065f46;" : "";
            
      out.write("\n");
      out.write("                        <div class=\"appointment-item\" style=\"border-left-color: ");
      out.print( colorBorde );
      out.write(";\">\n");
      out.write("                            <div class=\"appointment-info\">\n");
      out.write("                                <h4>");
      out.print( examinarTexto(especialidadCita) );
      out.write("</h4>\n");
      out.write("                                <p style=\"font-weight: 600; color: #475569; margin-top: 2px;\">👨‍⚕️ Dr(a). ");
      out.print( examinarTexto(medicoCita) );
      out.write("</p>\n");
      out.write("                                <p style=\"margin-top: 2px;\">🏥 ");
      out.print( examinarTexto(establecimientoCita) );
      out.write("</p>\n");
      out.write("                                <p style=\"margin-top: 2px;\">📅 ");
      out.print( fechaCita );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print( horaCita.substring(0, 5) );
      out.write("</p>    \n");
      out.write("                            </div>\n");
      out.write("                            <span class=\"status-badge\" style=\"");
      out.print( estiloBadge );
      out.write('"');
      out.write('>');
      out.print( estadoCita );
      out.write("</span>\n");
      out.write("                        </div>\n");
      out.write("            ");

                    }

                    if (!tieneCitas) {
                        out.println("<p style='color: #64748b; text-align: center; margin-top: 20px;'>Usted no cuenta con citas programadas actualmente.</p>");
                    }

                } catch(Exception e) {
                    out.println("<p style='color: red;'>Error al cargar el historial: " + e.getMessage() + "</p>");
                } finally {
                    if(rsCitas != null) rsCitas.close();
                    if(psCitas != null) psCitas.close();
                    if(conCitas != null) conCitas.close();
                }
            
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        const medicosData = [\n");
      out.write("            ");

                Connection conData = null;
                Statement stData = null;
                ResultSet rsData = null;
                try {
                    conData = Conexion.ConexionDB.conectar();
                    stData = conData.createStatement();
                    rsData = stData.executeQuery("SELECT id, nombres, especialidad, id_establecimiento FROM medicos");
                    boolean primero = true;
                    while(rsData.next()) {
                        if(!primero) out.print(",");
                        out.print("{id:" + rsData.getInt("id") + ", nombre:'" + rsData.getString("nombres") + "', esp:'" + rsData.getString("especialidad") + "', estId:" + rsData.getInt("id_establecimiento") + "}");
                        primero = false;
                    }
                } catch(Exception e) {} finally { if(rsData!=null)rsData.close(); if(stData!=null)stData.close(); if(conData!=null)conData.close(); }
            
      out.write("\n");
      out.write("        ];\n");
      out.write("\n");
      out.write("        function cargarEspecialidades() {\n");
      out.write("            const estId = document.getElementById(\"idEstablecimiento\").value;\n");
      out.write("            const espSelect = document.getElementById(\"especialidadSelect\");\n");
      out.write("            const medSelect = document.getElementById(\"idMedico\");\n");
      out.write("            \n");
      out.write("            espSelect.innerHTML = '<option value=\"\">-- Seleccione una especialidad --</option>';\n");
      out.write("            medSelect.innerHTML = '<option value=\"\">-- Primero elija una especialidad --</option>';\n");
      out.write("            medSelect.disabled = true;\n");
      out.write("\n");
      out.write("            if (!estId) {\n");
      out.write("                espSelect.disabled = true;\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            const especialidadesFiltradas = [...new Set(medicosData.filter(m => m.estId == estId).map(m => m.esp))];\n");
      out.write("            \n");
      out.write("            especialidadesFiltradas.forEach(esp => {\n");
      out.write("                const opt = document.createElement(\"option\");\n");
      out.write("                opt.value = esp;\n");
      out.write("                opt.textContent = esp;\n");
      out.write("                espSelect.appendChild(opt);\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            espSelect.disabled = false;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function cargarMedicos() {\n");
      out.write("            const estId = document.getElementById(\"idEstablecimiento\").value;\n");
      out.write("            const espNombre = document.getElementById(\"especialidadSelect\").value;\n");
      out.write("            const medSelect = document.getElementById(\"idMedico\");\n");
      out.write("\n");
      out.write("            medSelect.innerHTML = '<option value=\"\">-- Seleccione un médico --</option>';\n");
      out.write("\n");
      out.write("            if (!espNombre) {\n");
      out.write("                medSelect.disabled = true;\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            const medicosFiltrados = medicosData.filter(m => m.estId == estId && m.esp === espNombre);\n");
      out.write("\n");
      out.write("            medicosFiltrados.forEach(m => {\n");
      out.write("                const opt = document.createElement(\"option\");\n");
      out.write("                opt.value = m.id;\n");
      out.write("                opt.textContent = m.nombre;\n");
      out.write("                medSelect.appendChild(opt);\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            medSelect.disabled = false;\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
